### ISSUE TITLE
[Task]: Add additional parameter

### ISSUE THREAD

**Issue by solairen** [solairen/helm-chart-updater#9]
### What should be added?

Add parameter `additional`, which can add, e.g, dependencies 

The input parameters should look like this:

```yaml
(...) # other inputs
additional: |
  - name: some dependencies
    version: 1.0.0
  - name: other dependencies
     version: 2.2.2
```

This parameter should not be `required`.

### Component

Code
